controller_list:
  - name: fake_LeftLeg_controller
    joints:
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKnee
      - LAnklePitch
      - LAnkleRoll
  - name: fake_RightLeg_controller
    joints:
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKnee
      - RAnklePitch
      - RAnkleRoll
  - name: fake_Legs_controller
    joints:
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKnee
      - LAnklePitch
      - LAnkleRoll
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKnee
      - RAnklePitch
      - RAnkleRoll
  - name: fake_All_controller
    joints:
      - HeadPan
      - HeadTilt
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKnee
      - LAnklePitch
      - LAnkleRoll
      - LShoulderPitch
      - LShoulderRoll
      - LElbow
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKnee
      - RAnklePitch
      - RAnkleRoll
      - RShoulderPitch
      - RShoulderRoll
      - RElbow